name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make build
      - run: make package-install
      - run: make lint
      - run: make test
